/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        InputValidation inputValidation = new InputValidation();
        Scanner scanner = new Scanner(System.in);

        Integer result = inputValidation.Validate(scanner, 1,100,
                "\n\nEnter an input 1-100 \n", "Error! Something went wrong!",
                50, true);

        if (result != null){
            System.out.println("You entered the value: " + result);
        } else {
            System.out.println("You exited the program");
        }
        scanner.close();
    }
}